export const curreny = [
  { currency: "Indian rupee", price: "INR – ₹" },
  { currency: "Australian dollar", price: "AUD – $" },
  { currency: "Brazilian real", price: "BRL – R$" },
  { currency: "Bulgarian lev", price: "BGN – лв." },
  { currency: "Canadian dollar", price: "CAD – $" },
  { currency: "Chilean peso", price: "CLP – $" },
  { currency: "Chinese yuan", price: "CNY – ￥" },
  { currency: "Colombian peso", price: "COP – $" },
  { currency: "Costa Rican colon", price: "CRC – ₡" },
  { currency: "Croatian kuna", price: "HRK – kn" },
  { currency: "Czech koruna", price: "CZK – Kč" },
  { currency: "Danish krone", price: "DKK – kr" },
  { currency: "Egyptian pound", price: "EGP – ج.م" },
  { currency: "Emirati dirham", price: "AED – ﺩ.ﺇ" },
  { currency: "Euro", price: "EUR – €" },
  { currency: "Hong Kong dollar", price: "HKD – $" },
  { currency: "Hungarian forint", price: "HUF – Ft" },
  { currency: "Indonesian rupiah", price: "IDR – Rp" },
  { currency: "Israeli new shekel", price: "ILS – ₪" },
  { currency: "Japanese yen", price: "JPY – ¥" },
  { currency: "Kenyan shilling", price: "KES – KSh" },
  { currency: "Malaysian ringgit", price: "MYR – RM" },
  { currency: "Mexican peso", price: "MXN – $" },
  { currency: "Moroccan dirham", price: "MAD" },
  { currency: "New Taiwan dollar", price: "TWD – $" },
  { currency: "New Zealand dollar", price: "NZD – $" },
  { currency: "Norwegian krone", price: "NOK – kr" },
  { currency: "Peruvian sol", price: "PEN – S/" },
  { currency: "Philippine peso", price: "PHP – ₱" },
  { currency: "Polish zloty", price: "PLN – zł" },
  { currency: "Pound sterling", price: "GBP – £" },
  { currency: "Qatari riyal", price: "QAR – ر.ق" },
  { currency: "Romanian leu", price: "RON – lei" },
  { currency: "Saudi Arabian riyal", price: "SAR – SR" },
  { currency: "Singapore dollar", price: "SGD – $" },
  { currency: "South African rand", price: "ZAR – R" },
  { currency: "South Korean won", price: "KRW – ₩" },
  { currency: "Swedish krona", price: "SEK – kr" },
  { currency: "Swiss franc", price: "CHF" },
  { currency: "Thai baht", price: "THB – ฿" },
  { currency: "Turkish lira", price: "TRY – ₺" },
  { currency: "Ukrainian hryvnia", price: "UAH – ₴" },
  { currency: "United States dollar", price: "USD – $" },
  { currency: "Uruguayan peso", price: "UYU – $U" },
  { currency: "Vietnamese dong", price: "VND – ₫" },
];
